### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by pnalla015** [TranWare/Shuttle#1]
Here is my code to use the plugin but its not working.
var success = function(message) {
            alert("Success calling Shuttle.detectReader :\n"+message);
            Shuttle.getSwipe(function(msg){
                alert("Success calling Shuttle.getSwipe :\n"+msg);  
            },function(err){
                alert("Error calling Shuttle.getSwipe :\n"+err);
            });
        }
        var failure = function(message) {
            alert("Error calling Shuttle.detectReader :\n"+ message);
        }
        Shuttle.detectReader(success, failure);

Please help me if I am doing wrong.
Please add some documentation to use the plugin.

**Comment by kjkrum** [comment]
This plugin is unlicensed and unsupported.  It's only here at all because the Cordova/PhoneGap Web builder requires a public repo.
